// Flat config. The heavy lifting comes from the Nuxt-generated config in
// .nuxt/eslint.config.mjs (regenerated by `nuxt prepare`), which is
// project-aware: Vue, TypeScript, and Nuxt's auto-imports are all wired up.
import withNuxt from './.nuxt/eslint.config.mjs'

// Polyfill Object.groupBy (Node 21+) for Node 20, which this project targets.
// @nuxt/eslint's config composer (eslint-flat-config-utils) calls it while
// building the flat config; without this, `eslint .` throws on Node 20.
// Runs at load time, before ESLint evaluates the composer below.
if (typeof Object.groupBy !== 'function') {
  Object.groupBy = (items, keyFn) => {
    const out = Object.create(null)
    let i = 0
    for (const item of items) {
      const key = keyFn(item, i++)
      ;(out[key] ??= []).push(item)
    }
    return out
  }
}

export default withNuxt(
  {
    // The server routes flatten raw, untyped MLB Stats API JSON, so `any`
    // (and pick<any>) is intentional there — see server/utils/mlb.ts.
    files: ['server/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
)
